MAILGUN_API_KEY = 'your Mailgun private API'
SANDBOX_URL = 'your sandbox url'
SENDER_EMAIL = 'test@your sandbox url'
RECIPIENT_EMAIL = 'your mail id'
API_KEY = 'Bolt API key'
DEVICE_ID = 'Your Device ID'
